# Generated by Django 5.2.4 on 2025-07-22 12:09

import django.db.models.deletion
import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="Book",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("title", models.CharField(max_length=200, verbose_name="书名")),
                ("author", models.CharField(max_length=100, verbose_name="作者")),
                ("total_pages", models.PositiveIntegerField(verbose_name="总页数")),
                (
                    "status",
                    models.CharField(
                        choices=[
                            ("WANT_TO_READ", "想读"),
                            ("READING", "在读"),
                            ("FINISHED", "已读"),
                        ],
                        default="WANT_TO_READ",
                        max_length=20,
                        verbose_name="阅读状态",
                    ),
                ),
                (
                    "added_date",
                    models.DateTimeField(auto_now_add=True, verbose_name="添加日期"),
                ),
            ],
        ),
        migrations.CreateModel(
            name="ReadingLog",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("pages_read", models.PositiveIntegerField(verbose_name="阅读页数")),
                ("notes", models.TextField(blank=True, null=True, verbose_name="笔记")),
                (
                    "log_date",
                    models.DateField(
                        default=django.utils.timezone.now, verbose_name="记录日期"
                    ),
                ),
                (
                    "book",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="logs",
                        to="tracker.book",
                        verbose_name="书籍",
                    ),
                ),
            ],
        ),
    ]
