# Generated by Django 5.2.4 on 2025-07-22 15:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("tracker", "0001_initial"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="readinglog",
            name="pages_read",
        ),
        migrations.AddField(
            model_name="readinglog",
            name="end_page",
            field=models.PositiveIntegerField(default=0, verbose_name="结束页码"),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name="readinglog",
            name="start_page",
            field=models.PositiveIntegerField(default=0, verbose_name="起始页码"),
            preserve_default=False,
        ),
    ]
